import subprocess
import time
subprocess.run(["clear"])

if __name__=="__main__":
	while True:
		print(r"""
__     _______ _   _ _  __    _  _____   ____    _    ___   ____    _    ____    _    ____
\ \   / / ____| \ | | |/ /   / \|_   _| / ___|  / \  |_ _| / ___|  / \  / ___|  / \  |  _ \
 \ \ / /|  _| |  \| | ' /   / _ \ | |   \___ \ / _ \  | |  \___ \ / _ \| |  _  / _ \ | |_) |
  \ V / | |___| |\  | . \  / ___ \| |    ___) / ___ \ | |   ___) / ___ \ |_| |/ ___ \|  _ <
   \_/  |_____|_| \_|_|\_\/_/   \_\_|   |____/_/   \_\___| |____/_/   \_\____/_/   \_\_| \_\
   
LINKEDIN-----> https://www.linkedin.com/in/venkat-sai-sagar-%F0%9F%87%AE%F0%9F%87%B3-a04b0418b/
G-MAIL	-----> venkatsaisagar.github@gmail.com

""")
		print("\n\n\n\t1. SCANNING")
		print("\t2. SNIFFING")
		print("\t00. EXIT")
		a=int(input("\n\nplease select the above option:\n\n\t\033[31m(~/venkatsaisagar@S3N) $ \033[0m"))
		if a == 1:
			print("\n\nEntering into NETWORK SCANNING MODE:")
			print("Network scanning is a vital activity for maintaining the security and performance of any network.")
			print("")
			print("01. Simple scan")
			print("02. Quick scan")
			print("03. Full scan")
			print("04. Ports scan")
			print("05. FIREWALL/IDS EVASION")
			print("06. Hosts discover")
			print("00. BACK")
			snty=int(input("\n\nplease select the above option:\n\n\t\033[31m(~/venkatsaisagar@S3N) $ \033[0m"))
			if snty ==1:
				print("\n\nSMIPLE SCAN is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["xterm","-e","bash","-c","cd scan;bash 1.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif snty ==2:
				print("\n\nQUICK SCAN is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["xterm","-e","bash","-c","cd scan;bash 2.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif snty ==3:
				print("\n\nFULL SCAN is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["xterm","-e","bash","-c","cd scan;bash 3.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif snty ==4:
				print("\n\nPorts SCAN is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["xterm","-e","bash","-c","cd scan;bash 4.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif snty ==5:
				print("\n\nFIREWALL/IDS EVASION is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["xterm","-e","bash","-c","cd scan;bash 5.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif snty ==6:
				print("\n\nHOSTS DISCOVER is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["xterm","-e","bash","-c","cd scan;bash 6.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif snty==0:
				subprocess.run(["clear"])


		elif a == 2:
			print("\n\nEntering into NETWORK SNIFFING MODE:")	
			print("Network sniffing is a powerful techinuqe that allows you to capture and analyze network traffic passing through your computer or device.")
			print("")
			print("01. COMPLETE HOST's TRAFFIC.")
			print("02. SPECIFIC HOST.")
			print("03. SPECIFIC PROTOCOL SNIFFING.")
			print("04. COMPLETE NETWORK TRAFFIC.")
			print("05. CREDENTIALS SNIFFING.")
			print("06. SAVED TRAFFIC. ")
			print("00. BACK")
			sfty=int(input("\n\nplease select the above option:\n\n\t\033[31m(~/venkatsaisagar@S3N) $ \033[0m"))
			if sfty ==1:
				print("\n\nCOMPLETE HOST's TRAFFIC is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["konsole","-e","bash","-c","cd snif;bash 1.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif sfty ==2:
				print("\n\nSPECIFIC HOST is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["konsole","-e","bash","-c","cd snif;bash 2.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif sfty ==3:
				print("\n\nSPECIFIC PROTOCOL SNIFFING.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["konsole","-e","bash","-c","cd snif;bash 3.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif sfty ==4:
				print("\n\nCOMPLETE NETWORK TRAFFIC is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["konsole","-e","bash","-c","cd snif;bash 4.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif sfty ==5:
				print("\n\nCREDENTIALS SNIFFING is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["xterm","-e","bash","-c","cd snif;bash 5.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif sfty ==6:
				print("\n\nSAVED TRAFFIC FILES is in progress.")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				time.sleep(1)
				print(".")
				subprocess.run(["konsole","-e","bash","-c","cd snif;bash 6.sh; exec bash"])
				time.sleep(1)
				subprocess.run(['clear'])
			elif sfty==0:
				subprocess.run(["clear"])
		elif a==0:
			subprocess.run(["clear"])
			break
		else:
			print("\n\nusshuu; see the screen properly, is there any option",a,"above")
			
